// Insight Pitch — seed data: people, streams, proposals, comments, teams, change requests. Loaded as a classic <script> in <head>; top-level names are shared globals.
const PEOPLE={kai:{name:'Kai Moreno',initials:'KM'},rob:{name:'Rob Kessler',initials:'RK'},maya:{name:'Maya Chen',initials:'MC'},priya:{name:'Priya Raman',initials:'PR'},daniel:{name:'Daniel Okafor',initials:'DO'},lena:{name:'Lena Fischer',initials:'LF'},tomas:{name:'Tomás Herrera',initials:'TH'},sam:{name:'Sam Whitfield',initials:'SW'},jun:{name:'Jun Park',initials:'JP'},ava:{name:'Ava Moreau',initials:'AM'}};
let UID=100;const nid=()=>'c'+(UID++);
const ageOf=t=>{const m=/^(\d+)([hdw])$/.exec(t);return m?+m[1]*({h:60,d:1440,w:10080})[m[2]]:0;};
const CATS={question:{label:'Question',bg:'#e4ecf3',fg:'#2c5272',dot:'#3b6a8f'},concern:{label:'Concern',bg:'#f6ecd6',fg:'#7a5410',dot:'#b07a1f'},suggestion:{label:'Suggestion',bg:'#dfeeee',fg:'#245e66',dot:'#2f7680'},support:{label:'Support',bg:'#e2ebe4',fg:'#234a36',dot:'#2e5e45'},comment:{label:'Comment',bg:'#fbfaf7',fg:'#5d665f',dot:'#9a9f98'},offtopic:{label:'Off-topic',bg:'#fbfaf7',fg:'#5d665f',dot:'#9a9f98'}};
const CAT_ORDER=['question','concern','suggestion','support','comment','offtopic'];
const REASONS=['Off-topic','Inappropriate','Spam','Misleading'];
const FLAGS=[[/\b(idiot|stupid|moron|dumb|pathetic)\b/,'Abusive language','Insults break the community guidelines.'],[/\b(shut up|get lost)\b/,'Hostile language','Keep the tone civil, even when you disagree.'],[/\b(liar|clueless|incompetent)\b|no idea what/,'Personal attack','Comments should address the proposal, not the person behind it.'],[/\b(corrupt|crook|scam|bribe)/,'Unsupported accusation','Allegations of wrongdoing go to the integrity office with evidence.'],[/https?:\/\/|www\.|\.(com|net|biz)\b/,'Possible spam','Links to outside services are checked before they appear.']];
const jevFlag=text=>{const t=text.toLowerCase();for(const[re,flag,why] of FLAGS)if(re.test(t))return{flag:flag.replace(/^Possible /,'').replace(/^spam$/,'Spam'),why};const L=text.replace(/[^a-zA-Z]/g,'');if(L.length>15&&L.replace(/[^A-Z]/g,'').length/L.length>0.7)return{flag:'Shouting',why:'Messages in capitals read as shouting. Try sentence case.'};return{flag:null,why:''};};
const STOP=new Set('that this with from have will would could should about there their they them were been being which what when where while into than then also just only more most some such very your ours each other these those does make made like much many need needs well here think know anyone really'.split(' '));
const toks=s=>(s.toLowerCase().match(/[a-z]{4,}/g)||[]).filter(w=>!STOP.has(w)).map(w=>w.slice(0,5));
const jevCat=x=>{const t=x.toLowerCase().trim();if(/\?\s*$/.test(t)||/^(who|how|what|when|why|where|is|are|can|will|would|does|do|has)\b/.test(t))return'question';if(/\b(concern|worr\w*|risk|unclear|ambitious|too|problem|constraint|low|expensive|won.t|doesn.t)\b/.test(t))return'concern';if(/\b(should|suggest|consider|worth|instead|require|add|maybe|could)\b/.test(t))return'suggestion';if(/\b(good|great|support|agree|valuable|helpful|easier|love|thanks|welcome)\b/.test(t))return'support';return'comment';};
const jevFull=(text,p)=>{const f=jevFlag(text);const L=latest(p)||p.draft;const tw=new Set(toks(text));const secs=[{h:'',b:L.title+' '+L.summary}];L.body.split(/\n\s*\n/).forEach(x=>{x=x.trim();if(x.startsWith('## '))secs.push({h:x.slice(3),b:x.slice(3)});else secs[secs.length-1].b+=' '+x;});let best={h:'',n:0};secs.forEach(sc=>{const sw=new Set(toks(sc.b));let n=0;tw.forEach(w=>{if(sw.has(w))n++;});if(n>best.n)best={h:sc.h,n};});const rel=best.n===0?8:Math.min(94,15+best.n*25);let cat=jevCat(text);if(rel<20&&tw.size>=3)cat='offtopic';return{cat,rel,topic:best.h,flag:f.flag,why:f.why};};
const JEV_SEED=[['Phasing makes','support',92,'Proposal'],['Who maintains the access','question',88,'Access'],['The capital estimate','concern',84,'Cost and funding'],['Could some beds','suggestion',61,'Proposal'],['Does anyone know when','offtopic',6,''],['Typical. Priya','concern',30,'','Personal attack'],['A register is only useful','suggestion',86,'Proposal'],['The 30-day deadline','concern',80,'Proposal'],['Who checks food safety','question',74,'Local sourcing'],['The finance score seems low','concern',58,'Proposal'],['How will people without','question',82,'Proposal'],['Would the desks also','question',85,'The problem'],['Law students would','support',64,'Proposal'],['Moving coach parking','concern',83,'Protecting the site']];
const seedJev=text=>{const o=JEV_SEED.find(x=>text.startsWith(x[0]));const f=jevFlag(text);return o?{cat:o[1],rel:o[2],topic:o[3],flag:o[4]||f.flag}:{cat:null,rel:null,topic:'',flag:f.flag};};
const cm=(author,text,time,likes,replies=[])=>({id:nid(),author,text,time,age:ageOf(time),likes,liked:false,userFlag:null,jev:seedJev(text),replies:replies.map(r=>({id:nid(),author:r[0],text:r[1],time:r[2],age:ageOf(r[2]),likes:r[3],liked:false,userFlag:null,jev:seedJev(r[1])}))});
const COLORS=['#2e5e45','#2f7680','#3b6a8f','#4c5aa0','#7a3f5e','#a0522d','#8a5a2b','#5b7a2e'];
const STREAMS=[
 {id:'health',name:'Healthcare',desc:'Hospitals, public health, clinics and medical services.',color:'#2f7680',active:true,related:['finance','it']},
 {id:'finance',name:'Finance',desc:'Public budgets, taxation, procurement and spending.',color:'#8a5a2b',active:true,related:['health']},
 {id:'law',name:'Law & Justice',desc:'Legislation, courts, legal aid and regulation.',color:'#7a3f5e',active:true,related:['it']},
 {id:'it',name:'IT & Digital',desc:'Digital public services, data, connectivity and e-government.',color:'#4c5aa0',active:true,related:['health','law']},
 {id:'tourism',name:'Tourism',desc:'Visitor economy, heritage sites and destination promotion.',color:'#a0522d',active:true,related:['transport','env']},
 {id:'transport',name:'Transport',desc:'Roads, public transit, cycling and freight.',color:'#3b6a8f',active:true,related:['tourism','env']},
 {id:'env',name:'Environment',desc:'Climate, conservation, waste and clean energy.',color:'#5b7a2e',active:true,related:['tourism','transport']},
 {id:'edu',name:'Education',desc:'Schools, universities, skills and lifelong learning.',color:'#2e5e45',active:true,related:[]},
 {id:'agri',name:'Agriculture',desc:'Farming, food security and rural livelihoods.',color:'#8a5a2b',active:false,related:[]}
];

const P1a="## The problem\n\nAbout 340,000 people in the northern region live more than 70 km from a full-service hospital. Emergency patients travel an average of **95 minutes**, and the two existing clinics refer most cases out of the district ([regional referral data, 2025](https://health.example.gov/referrals-2025)).";
const P1cost="## Cost and funding\n\nThe estimated capital cost is 48 million. Annual running costs are estimated at 9 million.\n\n| Source | Share | Amount |\n| National health infrastructure fund | 60% | 28.8 million |\n| Provincial budget | 25% | 12 million |\n| Development bank loan | 15% | 7.2 million |\n\n::file Cost estimate breakdown.xlsx | 86 KB";
const P1v1=P1a+"\n\n## Proposal\n\nBuild a 200-bed district hospital with emergency, maternity, surgery and outpatient departments on the public land next to the regional health office.";
const P1v2=P1v1+"\n\n"+P1cost;
const P1v3=P1a+"\n\n## Proposal\n\nBuild a 200-bed district hospital on the public land next to the regional health office, in two phases:\n\n1. **Phase 1**, within 18 months: outpatient, maternity and emergency care.\n2. **Phase 2**: surgery and inpatient wards.\n\n::image p1-site | The proposed site, looking north from the regional health office | Level open land beside a two-storey office building, bordered by the regional road on the east side | 240 KB\n\n"+P1cost+"\n\n## Access\n\nThe site needs a 3 km upgraded access road and a bus stop on the regional route. The provincial roads authority would deliver the road alongside Phase 1.\n\n::video https://www.youtube.com/watch?v=northern-site | Walk-through of the proposed site and access route | 3:12\n\n::file Site survey report.pdf | 1.4 MB";
const T1='Build a 200-bed district hospital in the northern region',S1='The nearest full-service hospital is 70 km away for 340,000 residents. A district hospital would cut emergency travel times by more than half.';
const P2why="## Why\n\nCitizens currently need a formal information request to see most government contracts, and responses take an average of 11 weeks.";
const P2v1=P2why+"\n\n## Proposal\n\nPublish every signed contract above 5 million, with amendments and the winning bid, in a searchable online register within 30 days of signing.";
const P2v2=P2why+"\n\n## Proposal\n\nPublish every signed contract above 1 million, with amendments and the winning bid, in a searchable online register within 30 days of signing.\n\n## Redaction\n\nPersonal data and genuinely security-sensitive clauses may be redacted. Each redaction must cite its legal basis, and the redaction log is itself public.";
const P3v1="## Proposal\n\nProvide a free daily meal to every primary school student in the district, starting with the 40 schools with the highest absence rates.\n\n## Local sourcing\n\nAt least 40% of produce would be bought from farms within the district through simplified, published tenders.\n\n## Expected outcomes\n\nHigher attendance, better nutrition indicators in annual health checks, and a stable buyer for small farms.";
const T5='Free legal aid clinics at every district court',S5='Free first-line legal advice for people who come to court without a lawyer.';
const P5prob="## The problem\n\nMore than half of people appearing in district courts for civil matters have no legal representation. Many cannot afford a lawyer and don't know that free help exists.";
const P5fund="## Funding\n\nThe bar association has offered volunteer hours. The remaining cost, mainly coordination staff and desk space, is about **600,000 a year**.";
const P5v1=P5prob+"\n\n## Proposal\n\nOpen a free legal aid desk in every district court, staffed two days a week by volunteer lawyers and supervised law students.\n\n"+P5fund;
const P5dan=P5v1.replace("Many cannot afford a lawyer and don't know that free help exists.","Many cannot afford a lawyer, and most don't know that free help exists.\n\nMost of these cases are family, tenancy and debt disputes, where the other side often has a lawyer. The desks would advise on all three.");
const P5sam=P5v1.replace('staffed two days a week by volunteer lawyers and supervised law students.','staffed two days a week by volunteer lawyers and final-year law students supervised by a practising lawyer.');
const P1maya=P1v3.replace('alongside Phase 1.','alongside Phase 1 and maintain it afterwards from its regular maintenance budget.');
const P5draft=P5prob+"\n\n## Proposal\n\nOpen a free legal aid desk in every district court, staffed three days a week by volunteer lawyers and supervised law students, with one full-time coordinator for the programme.\n\n"+P5fund+"\n\n| Item | Per year |\n| Coordinator (1 full-time) | 380,000 |\n| Desk space and equipment | 140,000 |\n| Training for law students | 80,000 |\n\n## Measuring success\n\n- Share of civil cases with some form of legal advice\n- Number of cases resolved before a full hearing\n\n::file Bar association letter of support.pdf | 210 KB";
const P4v1="## Proposal\n\nCreate a signed 4 km walking trail linking the old town's twelve listed buildings, with a small visitor centre in the former customs house.";
const P4v2=P4v1+"\n\n## Why now\n\nVisitor numbers have grown 30% in three years, but most visitors stay less than half a day. A trail gives them reasons to stay longer and spreads spending beyond the main square.\n\n## Protecting the site\n\nThe trail uses existing streets. Coach parking moves to the edge of the old town, with a shuttle to the visitor centre.";
const P7v1="## Proposal\n\nRun a 12-month pilot replacing diesel buses with 14 electric buses on routes 4 and 11, the two busiest city routes.\n\n## Costs\n\nThe buses are leased, so capital cost is limited to two depot charging stations. Fuel and maintenance savings are expected to cover about 70% of the lease.\n\n## What we'd measure\n\nReliability, operating cost per kilometre, air quality on both routes, and passenger satisfaction.";
const P8v1="## The problem\n\nLand disputes make up roughly a third of civil cases in district courts. Most come from paper records that are incomplete, duplicated or lost.\n\n## Proposal\n\nDigitise the land registry over three years, starting with the districts with the most disputes. Every title gets a unique ID, a mapped boundary and a full ownership history that owners can check online.";
const P6draft="## The problem\n\nRural health centres often have a nurse but no doctor on site. Patients travel to the district hospital for consultations that could happen remotely.\n\n## Proposal\n\nInstall telemedicine kiosks in 25 rural health centres, connecting nurses and patients to on-call doctors at the district hospital by video.";

const v=(n,date,note,title,summary,body)=>({v:n,date,note,title,summary,body});
const SEED=[
 {id:'p1',author:'priya',scores:{health:9,finance:6,transport:3},ts:10,updated:'2 days ago',draft:null,following:false,
  versions:[v(1,'Sep 12','Initial version',T1,S1,P1v1),v(2,'Sep 20','Added cost and funding sources',T1,S1,P1v2),v(3,'Sep 30','Split construction into two phases; added access road plan',T1,S1,P1v3)],
  comments:[
   cm('daniel','Phasing makes this much easier to fund. Good to see the outpatient wing opening first.','2d',6,[['priya','That was the main feedback from the v2 consultation. Thanks for pushing on it.','2d',2],['lena','@Daniel Okafor the regional health board said the same at the last public meeting.','1d',3],['sam','Staffing is the real constraint. Is there a recruitment plan for doctors and nurses?','1d',4]]),
   cm('jun','Who maintains the access road after construction? The last project left that unclear.','1d',4,[['priya','The provincial roads authority. I’ll name them explicitly in the next version.','1d',1],['kai','Cheap bridging loans for contractors, message me at www.quickbuild-loans.example','20h',0]]),
   cm('ava','The capital estimate looks low compared with similar hospitals built in the last five years.','20h',2),
   cm('sam','Could some beds be reserved for long-term care? The population is ageing faster than the forecasts assumed.','6h',1,[['tomas','Worth a separate proposal. It would change the finance score quite a bit.','5h',5]]),
   cm('kai','Does anyone know when the summer festival dates get announced?','10h',0),
   cm('rob','Typical. Priya clearly has no idea what she’s doing and is padding her CV with this.','3h',0)
  ]},
 {id:'p2',author:'daniel',scores:{finance:9,law:7,it:5},ts:9,updated:'3 days ago',draft:null,following:false,
  versions:[v(1,'Sep 18','Initial version','Publish all public procurement contracts online within 30 days','Every signed government contract, with its amendments, in a searchable open register.',P2v1),v(2,'Sep 29','Lowered threshold to 1 million; added redaction rules','Publish all public procurement contracts online within 30 days','Every signed government contract, with its amendments, in a searchable open register.',P2v2)],
  comments:[cm('lena','A register is only useful if the data is structured. Can we require a standard format?','3d',3,[['daniel','Yes. Contracts would follow an open data standard so they can be compared across agencies.','3d',2]]),cm('jun','The 30-day deadline is ambitious for smaller municipalities.','2d',4)]},
 {id:'p3',author:'lena',scores:{edu:8,health:5,finance:4,env:3},ts:8,updated:'5 days ago',draft:null,following:true,
  versions:[v(1,'Sep 27','Initial version','Free school meals sourced from local farms','A daily meal for every primary student, with at least 40% of produce bought from farms in the district.',P3v1)],
  comments:[cm('priya','Who checks food safety for the smaller suppliers?','4d',2),cm('ava','The finance score seems low given the cost of a daily meal at this scale.','4d',1)]},
 {id:'p8',author:'jun',scores:{law:8,it:9,finance:4},ts:7.5,updated:'6 days ago',draft:null,following:false,
  versions:[v(1,'Sep 26','Initial version','Digital land registry to reduce property disputes','Move land titles from paper to a public digital registry, starting where disputes are most common.',P8v1)],
  comments:[cm('lena','How will people without internet access check their titles?','5d',3)]},
 {id:'p5',author:'maya',scores:{law:9,finance:4},ts:7,updated:'1 week ago',following:false,
  draft:{title:'Free legal aid clinics at every district court',summary:'Free first-line legal advice for people who come to court without a lawyer.',body:P5draft,saved:'yesterday'},
  versions:[v(1,'Sep 24','Initial version','Free legal aid clinics at every district court','Free first-line legal advice for people who come to court without a lawyer.',P5v1)],
  comments:[cm('daniel','Would the desks also help with family and tenancy cases? That’s where most unrepresented people are.','6d',2,[['maya','Yes, civil matters broadly. I’ll make that explicit in the next version.','5d',1]]),cm('sam','Law students would get valuable experience from this too.','5d',3)]},
 {id:'p4',author:'tomas',scores:{tourism:9,transport:4,env:3,finance:3},ts:6,updated:'2 weeks ago',draft:null,following:false,
  versions:[v(1,'Sep 10','Initial version','Heritage trail and visitor centre for the old town','A signed walking trail through the old town’s listed buildings, with a visitor centre in the former customs house.',P4v1),v(2,'Sep 16','Added rationale and site protection measures','Heritage trail and visitor centre for the old town','A signed walking trail through the old town’s listed buildings, with a visitor centre in the former customs house.',P4v2)],
  comments:[cm('ava','Moving coach parking will need consultation with shop owners on the main square.','2w',2,[['tomas','Agreed. A session with the traders’ association is planned for next month.','2w',0]])]},
 {id:'p7',author:'sam',scores:{transport:9,env:8,finance:4},ts:5,updated:'3 weeks ago',draft:null,following:false,
  versions:[v(1,'Sep 8','Initial version','Electric bus pilot on two city routes','Lease 14 electric buses for a year on the two busiest routes and measure cost, reliability and air quality.',P7v1)],comments:[]},
 {id:'p6',author:'maya',scores:{health:8,it:7},ts:4,updated:'4 days ago',following:false,versions:[],comments:[],
  draft:{title:'Telemedicine kiosks for rural health centres',summary:'Connect rural nurses and patients to district hospital doctors by video.',body:P6draft,saved:'4 days ago'}}
];
const INSIGHT_SEED={
 p1:[['concern','No recruitment plan yet for the doctors and nurses the hospital needs',9,['Staffing is the real']],['concern','The capital estimate looks low against hospitals built in the last five years',7,['The capital estimate']],['suggestion','Reserve some beds for long-term care',5,['Could some beds','Worth a separate']],['clarification','Who maintains the access road after construction?',4,['Who maintains the access'],true]],
 p2:[['concern','A 30-day deadline may be hard for smaller municipalities',4,['The 30-day deadline']],['suggestion','Require a standard open data format for published contracts',3,['A register is only']]],
 p3:[['concern','The finance score looks low for a daily meal at this scale',1,['The finance score']],['clarification','Who checks food safety for the smaller suppliers?',2,['Who checks food']]],
 p8:[['clarification','How will people without internet access check their titles?',3,['How will people']]],
 p5:[['clarification','Will the desks cover family and tenancy cases?',2,['Would the desks']]],
 p4:[['concern','Moving coach parking needs consultation with shop owners on the main square',2,['Moving coach parking']]]
};
const findSrc=(p,pre)=>{for(const c of p.comments){if(c.text.startsWith(pre))return{cid:c.id};for(const r of c.replies)if(r.text.startsWith(pre))return{cid:c.id,rid:r.id};}return null;};
SEED.forEach(p=>{p.insights=(INSIGHT_SEED[p.id]||[]).map(([kind,text,votes,pres,answered])=>({id:nid(),kind,text,votes,voted:false,answered:!!answered,src:pres.map(x=>findSrc(p,x)).filter(Boolean)}));});
const tm=(lead,members,o={})=>({lead,founder:o.founder||lead,members:[{id:lead,focus:null,since:''},...members.map(m=>({id:m[0],focus:m[1]||null,since:m[2]||''}))],joinMode:o.mode||'roles',cap:o.cap||null,openRoles:(o.roles||[]).map(r=>({id:nid(),stream:r[0],note:r[1]})),requests:(o.req||[]).map(r=>({id:nid(),user:r[0],stream:r[1]||null,note:r[2],time:r[3]})),invites:(o.inv||[]).map(r=>({id:nid(),user:r[0],stream:r[1]||null,note:r[2],time:r[3],from:lead})),blocked:o.blocked||[],declined:o.declined||{},offer:o.offer||null});
const TEAMS={
 p1:tm('priya',[['ava','finance','Sep 21'],['maya',null,'Sep 25']],{roles:[['transport','Plan the access road and the bus link to the regional route']],offer:{to:'maya',note:'I move to the national planning office in November. You know the funding side best.',time:'1d'}}),
 p2:tm('daniel',[['lena','it','Sep 22']],{mode:'open'}),
 p3:tm('lena',[],{mode:'closed'}),
 p8:tm('jun',[],{roles:[['law','Draft the dispute rules for contested titles'],['finance','Estimate the three-year cost']],req:[['maya','law','I drafted the legal aid proposal and work with the district courts on civil cases.','2d']]}),
 p5:tm('maya',[['daniel','law','Sep 25'],['sam',null,'Sep 26']],{cap:6,roles:[['finance','Check the coordinator and desk costs, and find a budget line']],req:[['ava','finance','Forty years costing public buildings. Happy to check the coordinator and desk space costs line by line.','5h'],['kai','finance','add me pls want to be on this','1h']],inv:[['jun','it','Could you advise on a simple case log the desks could share?','1d']]}),
 p4:tm('tomas',[],{roles:[['transport','Plan coach parking and the shuttle']],declined:{maya:12}}),
 p7:tm('sam',[],{roles:[['finance','Review the lease terms and the savings estimate']],inv:[['maya','finance','Could you look at the lease and procurement terms before v2?','3h']]}),
 p6:tm('maya',[])
};
const CRS={
 p5:[{id:'cr1',author:'daniel',base:1,title:T5,summary:S5,body:P5dan,note:'Named the case types the desks would cover',time:'2d',status:'open'},{id:'cr2',author:'sam',base:1,title:T5,summary:S5,body:P5sam,note:'Law students to be supervised by a practising lawyer',time:'20h',status:'open'}],
 p1:[{id:'cr3',author:'maya',base:3,title:T1,summary:S1,body:P1maya,note:'Named who maintains the access road after construction',time:'1d',status:'open'}]
};
SEED.forEach(p=>{p.team=TEAMS[p.id];p.changeRequests=CRS[p.id]||[];});
const ME='maya';
const PROFILE={"kai":["Citizen","","","Western district","Aug 2026","",["en"]],"rob":["Citizen","","","Central district","Sep 2026","",["en"]],"maya":["Admin","Policy advisor","Ministry of Public Administration","Capital district","Jan 2025","I run the Insight Pitch programme and draft proposals on access to justice and rural health.",["en","si"]],"priya":["Official","Health infrastructure planner","Regional Health Office","Northern region","Mar 2025","I plan hospital and clinic capacity for the northern region. Most of my proposals start from referral and travel-time data.",["en","si"]],"daniel":["Citizen","Volunteer","Open Contracting Network","Capital district","Apr 2025","Procurement transparency volunteer. I read contracts so others don’t have to.",["en","fr"]],"lena":["Citizen","School board member","","Eastern district","May 2025","Parent of two and member of the district school board.",["en","es"]],"tomas":["Official","Heritage officer","Old Town Municipal Council","Old Town","Feb 2025","I look after the old town’s listed buildings and work with traders on visitor plans.",["en","es","pt"]],"sam":["Citizen","Transport engineer","","Capital district","Jun 2025","Civil engineer working on public transit. Interested in anything that moves people more reliably.",["en"]],"jun":["Official","Records modernisation lead","Land Registry Department","Capital district","Mar 2025","Leading the move from paper land titles to digital records.",["en"]],"ava":["Citizen","Retired quantity surveyor","","Southern district","Jul 2025","Forty years of costing public buildings. I check whether the numbers add up.",["en","fr"]]};
Object.entries(PROFILE).forEach(([k,a])=>Object.assign(PEOPLE[k],{role:a[0],title:a[1],org:a[2],location:a[3],joined:a[4],bio:a[5],langs:a[6]}));
const ROLE_STYLE={Admin:{bg:'#e2ebe4',fg:'#234a36'},Official:{bg:'#e4ecf3',fg:'#2c5272'},Citizen:{bg:'#ecebe4',fg:'#3a423c'}};
